In [1]:
import numpy as np
#i)
V=QQ^4
def f(v):
    x=v[0]
    y=v[1]
    z=v[2]
    w=v[3]
    
    a=(-2*x + y + 4*z -2*w)/3
    b=(3*x - 6*y + 6*z)/3
    c=(2*x - 4*y + 5*z +2*w)/3
    d=(-6*y + 6*z + 3*w)/3
    
    R=vector(QQ, [a,b,c,d])
    
    return R

In [2]:
A=column_matrix(QQ, [f([1,0,0,0]),f([0,1,0,0]),f([0,0,1,0]),f([0,0,0,1])])
A

[-2/3  1/3  4/3 -2/3]
[   1   -2    2    0]
[ 2/3 -4/3  5/3  2/3]
[   0   -2    2    1]

In [3]:
#Factorizacion del polinomio
t=PolynomialRing(RationalField(), 't').gen()
P=A.charpoly('t')
factor(P)

(t - 1) * (t + 1) * (t^2 - 3)

In [4]:
P1=factor(P)[0][0]^factor(P)[0][1]
P2=factor(P)[1][0]^factor(P)[1][1] 
P3=factor(P)[2][0]^factor(P)[2][1] 

print(P1,P2,P3)

(t - 1, t + 1, t^2 - 3)


In [5]:
R1=P/P1
R2=P/P2
R3=P/P3

In [6]:
def MCD(POLINOMIOS):
    if(len(POLINOMIOS)==2):
        return xgcd(POLINOMIOS[0], POLINOMIOS[1])
    else:
        RESP=[]
        P1=POLINOMIOS[0]
        RESTO = POLINOMIOS[1:]
        d=MCD([P1, MCD(RESTO)[0]])[0]
        Q1=MCD([P1, MCD(RESTO)[0]])[1]
        Q=MCD([P1, MCD(RESTO)[0]])[2]
        RESP.append(d)
        RESP.append(Q1)
        for i in range(2,len(POLINOMIOS)+1):
            RESP.append(Q*MCD(RESTO)[i-1])
        return RESP

In [13]:
Q1=MCD([R1,R2,R3])[1]
Q2=MCD([R1,R2,R3])[2]
Q3=MCD([R1,R2,R3])[3]

Pi1=Q1*R1
Pi2=Q2*R2
Pi3=Q3*R3

print(factor(Pi1), factor(Pi2), factor(Pi3))

((-1/4) * (t + 1) * (t^2 - 3), (-1/8) * (t - 1) * (t^2 - 3) * (t^2 + 2*t - 1), (1/8) * (t + 1) * (t - 1)^2 * (t^2 + 2*t - 1))


In [12]:
Pi1(A)+Pi2(A)+Pi3(A)

[1 0 0 0]
[0 1 0 0]
[0 0 1 0]
[0 0 0 1]

In [87]:
P1(A).right_kernel()

Vector space of degree 4 and dimension 1 over Rational Field
Basis matrix:
[1 1 1 0]

In [88]:
P2(A).right_kernel()

Vector space of degree 4 and dimension 1 over Rational Field
Basis matrix:
[1 1 0 1]

In [89]:
P3(A).right_kernel()

Vector space of degree 4 and dimension 2 over Rational Field
Basis matrix:
[1 0 1 1]
[0 1 1 1]

In [90]:
BaC=column_matrix(QQ, [[1,0,1,1],[0,1,1,1],[1,1,0,1],[1,1,1,0]])
CaB=(BaC)^-1

In [91]:
CaB*A*BaC

[ 0  1  0  0]
[ 3  0  0  0]
[ 0  0 -1  0]
[ 0  0  0  1]

In [98]:
#ii) Lo mismo pero sobre R
A

[-2/3  1/3  4/3 -2/3]
[   1   -2    2    0]
[ 2/3 -4/3  5/3  2/3]
[   0   -2    2    1]

In [99]:
#Factorizacion del polinomio
t=PolynomialRing(RationalField(), 't').gen()
P=A.charpoly('t')

P1=factor(P)[0][0]^factor(P)[0][1]
P2=factor(P)[1][0]^factor(P)[1][1] 
P3=factor(P)[2][0]^factor(P)[2][1] 


print(P1,P2,P3)

(t - 1, t + 1, t^2 - 3)


In [100]:
#Agregarle sqrt(3) al cuerpo
K.<r> = QQ.extension(P3)

In [106]:
#Ahora sí
P=P.change_ring(K)
factor(P)

P1=factor(P)[0][0]^factor(P)[0][1]
P2=factor(P)[1][0]^factor(P)[1][1] 
P3=factor(P)[2][0]^factor(P)[2][1] 
P4=factor(P)[3][0]^factor(P)[3][1] 

print(P1,P2,P3,P4, 'donde r=sqrt(3)')

(t - r, t - 1, t + 1, t + r, 'donde r=sqrt(3)')


In [107]:
R1=P/P1
R2=P/P2
R3=P/P3
R4=P/P4

In [110]:
Q1=MCD([R1,R2,R3,R4])[1]
Q2=MCD([R1,R2,R3,R4])[2]
Q3=MCD([R1,R2,R3,R4])[3]
Q4=MCD([R1,R2,R3,R4])[4]

Pi1=Q1*R1
Pi2=Q2*R2
Pi3=Q3*R3
Pi4=Q4*R4

print(factor(Pi1), factor(Pi2), factor(Pi3), factor(Pi4))

((1/12*r) * (t - 1) * (t + 1) * (t + r), (1/48*r - 1/16) * (t - r) * (t + 1) * (t + r) * (t^2 + 2*r*t + 5), (1/48*r) * (t - r) * (t - 1) * (t + r) * (t + r + 2) * (t^2 + 2*r*t + 5), (-1/48*r) * (t - r) * (t - 1) * (t + 1) * (t + r + 2) * (t^2 + 2*r*t + 5))


In [112]:
P1(A).right_kernel()

Vector space of degree 4 and dimension 1 over Number Field in r with defining polynomial t^2 - 3
Basis matrix:
[    1     r r + 1 r + 1]

In [116]:
P2(A).right_kernel()

Vector space of degree 4 and dimension 1 over Number Field in r with defining polynomial t^2 - 3
Basis matrix:
[1 1 1 0]

In [117]:
P3(A).right_kernel()

Vector space of degree 4 and dimension 1 over Number Field in r with defining polynomial t^2 - 3
Basis matrix:
[1 1 0 1]

In [118]:
P4(A).right_kernel()

Vector space of degree 4 and dimension 1 over Number Field in r with defining polynomial t^2 - 3
Basis matrix:
[     1     -r -r + 1 -r + 1]

In [120]:
BaC = column_matrix(K, [[1,r,r+1,r+1],[1,1,1,0],[1,1,0,1],[1,-r,-r+1,-r+1]])
CaB=(BaC)^-1

In [121]:
CaB*A*BaC

[ r  0  0  0]
[ 0  1  0  0]
[ 0  0 -1  0]
[ 0  0  0 -r]

In [122]:
#iii)
V=QQ^4
def f(v):
    x=v[0]
    y=v[1]
    z=v[2]
    w=v[3]
    
    a=(9*x - 3*y - 6*w)/3
    b=(3*x - 3*y + 6*z)/3
    c=(8*x - 10*y + 5*z - w)/3
    d=(10*x - 8*y + z + w)/3
    
    R=vector(QQ, [a,b,c,d])
    
    return R

In [123]:
A=column_matrix(QQ, [f([1,0,0,0]),f([0,1,0,0]),f([0,0,1,0]),f([0,0,0,1])])
A

[    3    -1     0    -2]
[    1    -1     2     0]
[  8/3 -10/3   5/3  -1/3]
[ 10/3  -8/3   1/3   1/3]

In [124]:
#Factorizacion del polinomio
t=PolynomialRing(RationalField(), 't').gen()
P=A.charpoly('t')
factor(P)

(t^2 - 2*t + 2) * (t^2 - 2*t + 10)

In [130]:
P1=factor(P)[0][0]^factor(P)[0][1]
P2=factor(P)[1][0]^factor(P)[1][1] 


print(P1,P2)

(t^2 - 2*t + 2, t^2 - 2*t + 10)


In [131]:
R1=P/P1
R2=P/P2

In [134]:
Q1=MCD([R1,R2])[1]
Q2=MCD([R1,R2])[2]


Pi1=Q1*R1
Pi2=Q2*R2


print(factor(Pi1), factor(Pi2))

((1/8) * (t^2 - 2*t + 10), (-1/8) * (t^2 - 2*t + 2))


In [136]:
P1(A).right_kernel()

Vector space of degree 4 and dimension 2 over Rational Field
Basis matrix:
[ 1  1  0  1]
[ 0  0  1 -1]

In [137]:
P2(A).right_kernel()

Vector space of degree 4 and dimension 2 over Rational Field
Basis matrix:
[1 0 1 1]
[0 1 1 1]

In [138]:
BaC=column_matrix(QQ, [[1,1,0,1],[0,0,1,-1],[1,0,1,1],[0,1,1,1]])
CaB=(BaC)^-1

In [139]:
CaB*A*BaC

[ 0  2  0  0]
[-1  2  0  0]
[ 0  0  1 -3]
[ 0  0  3  1]

In [140]:
#iv) lo mismo pero sobre C
A

[    3    -1     0    -2]
[    1    -1     2     0]
[  8/3 -10/3   5/3  -1/3]
[ 10/3  -8/3   1/3   1/3]

In [141]:
#Factorizacion del polinomio
t=PolynomialRing(RationalField(), 't').gen()
P=A.charpoly('t')
factor(P)

(t^2 - 2*t + 2) * (t^2 - 2*t + 10)

In [144]:
#Agregarle i al cuerpo
K.<i> = QQ.extension(t^2 + 1)
P=P.change_ring(K)

factor(P)

(t - 3*i - 1) * (t - i - 1) * (t + i - 1) * (t + 3*i - 1)

In [147]:
#Ahora sí
P1=factor(P)[0][0]^factor(P)[0][1]
P2=factor(P)[1][0]^factor(P)[1][1] 
P3=factor(P)[2][0]^factor(P)[2][1] 
P4=factor(P)[3][0]^factor(P)[3][1] 

print(P1,P2,P3,P4)

(t - 3*i - 1, t - i - 1, t + i - 1, t + 3*i - 1)


In [148]:
R1=P/P1
R2=P/P2
R3=P/P3
R4=P/P4

In [149]:
Q1=MCD([R1,R2,R3,R4])[1]
Q2=MCD([R1,R2,R3,R4])[2]
Q3=MCD([R1,R2,R3,R4])[3]
Q4=MCD([R1,R2,R3,R4])[4]

Pi1=Q1*R1
Pi2=Q2*R2
Pi3=Q3*R3
Pi4=Q4*R4

print(factor(Pi1), factor(Pi2), factor(Pi3), factor(Pi4))

((1/48*i) * (t - i - 1) * (t + i - 1) * (t + 3*i - 1), (1/384*i) * (t - 3*i - 1) * (t + i - 1) * (t + 3*i - 1) * (t^2 + (6*i - 2)*t - 6*i - 16), (-1/768) * (t - 3*i - 1) * (t - i - 1) * (t + 3*i - 1) * (t + 5*i - 1) * (t^2 + (6*i - 2)*t - 6*i - 16), (1/768) * (t - 3*i - 1) * (t - i - 1) * (t + i - 1) * (t + 5*i - 1) * (t^2 + (6*i - 2)*t - 6*i - 16))


In [150]:
P1(A).right_kernel()

Vector space of degree 4 and dimension 1 over Number Field in i with defining polynomial t^2 + 1
Basis matrix:
[     1     -i -i + 1 -i + 1]

In [151]:
P2(A).right_kernel()

Vector space of degree 4 and dimension 1 over Number Field in i with defining polynomial t^2 + 1
Basis matrix:
[           1            1  1/2*i + 1/2 -1/2*i + 1/2]

In [152]:
P3(A).right_kernel()

Vector space of degree 4 and dimension 1 over Number Field in i with defining polynomial t^2 + 1
Basis matrix:
[           1            1 -1/2*i + 1/2  1/2*i + 1/2]

In [158]:
P4(A).right_kernel()

Vector space of degree 4 and dimension 1 over Number Field in i with defining polynomial t^2 + 1
Basis matrix:
[    1     i i + 1 i + 1]

In [159]:
BaC = column_matrix(K, [[1,-i,-i+1, -i+1],[1,1,1/2*i + 1/2, -1/2*i + 1/2],[1,1,-1/2*i + 1/2,1/2*i + 1/2],[1,i,i+1,i+1]])
CaB=(BaC)^-1

In [160]:
CaB*A*BaC

[ 3*i + 1        0        0        0]
[       0    i + 1        0        0]
[       0        0   -i + 1        0]
[       0        0        0 -3*i + 1]